### ISSUE TITLE
need to addon .csv file support also 

### ISSUE THREAD

**Issue by Awinashdelhi** [rimoun-g/Excel_Multi_File_Replacer-Autoit#1]
Sir,

Please addon .csv file support also as my files is in .csv format and currently not supporting ,
So please if possible from your side to addon .csv support also **Please Sir**..

I'll be very thankful to you for this 

Thanks in Advance Sir 

Great Work

**Comment by sven-seyfert** [comment]
Hi @Awinashdelhi ,

*.csv files are plain text files which could be opened with any default editor. In case you are using VSCode (my recommendation) or Notepad++ or Sublime etc., you can open all your *.csv files in the editor and do a simple search and replace there. No need to involve any language or technology.

Best regards
Sven

**Comment by Awinashdelhi** [comment]
Thanks @Sven-Seyfert  ,

but i had to in 5000+ .csv at once and it's a daily work to do in 5000+ .csv file 

Now i changed the above code to support .csv  now it's fully working.
